public enum Filling {
    HAZELNUT,ALMOND,PISTACHIO,CARAMEL,LIQUEUR,ALCOHOLIC,NOUN
}

public enum Shape {
    TRUFFLE,DOME,SQUARE,OVAL,BAR,CUSTOMSHAPE
}

public enum ChocolateType {
    DARK,MILK,WHITE,ALCOHOLIC,BLONDE
}

public enum OrderStatus {
    DESIGNED,CONFIRMED,PRODUCTING,DELIVERING,FINISHED
}